#!/usr/bin/env python3.11
"""build_htaccess.py - generate an Apache .htaccess for the new site.

Emits 301 redirects from every DokuWiki URL to its MkDocs equivalent, plus
catch-all rules for DokuWiki's special endpoints (/_media/, doku.php, etc.)
and dropped namespaces (fr/, wiki/, playground/).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from dw_paths import (
    DROP_NAMESPACES,
    dokuwiki_id_to_new_path,
    dokuwiki_id_to_old_url,
    dokuwiki_id_to_url,
    iter_source_pages,
)


PREAMBLE = """# Generated by scripts/build_htaccess.py - do not edit by hand.
# DokuWiki -> MkDocs 301 redirects for bsdrp.net.

RewriteEngine on
RewriteBase /

# Canonical host + HTTPS
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{SERVER_NAME}/$1 [R=301,L]
RewriteCond %{HTTP_HOST} ^www\\.bsdrp\\.net [NC]
RewriteRule ^(.*)$ https://bsdrp.net/$1 [R=301,L]

# DokuWiki home aliases
RewriteRule ^bsdrp/?$ / [R=301,L]
RewriteRule ^doku\\.php$ / [R=301,L]
RewriteRule ^index\\.php$ / [R=301,L]
RewriteRule ^feed\\.php.*$ / [R=301,L]

# DokuWiki internal endpoints we no longer serve
RewriteRule ^lib/.*$ / [R=301,L]
RewriteRule ^_detail/.*$ / [R=301,L]
RewriteRule ^_export/.*$ / [R=301,L]

# Media URLs: DokuWiki served them under /_media/<path>; we serve under
# /assets/images/<path>. The wiki/ subtree of media is dropped.
RewriteRule ^_media/wiki/.*$ / [R=301,L]
RewriteRule ^_media/(.+)$ /assets/images/$1 [R=301,L]

"""


DROP_BLOCK = """
# Dropped namespaces (French, DokuWiki built-in pages, sandbox) -> home
"""


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--pages", required=True, type=Path)
    p.add_argument("--out", required=True, type=Path)
    args = p.parse_args(argv)

    kept: list[tuple[str, str]] = []  # (old_url, new_url)
    for _src, dw_id in iter_source_pages(args.pages):
        if any(dw_id == ns or dw_id.startswith(ns + ":") for ns in DROP_NAMESPACES):
            continue
        if dw_id == "bsdrp":
            continue  # already in preamble
        old = dokuwiki_id_to_old_url(dw_id)
        new = dokuwiki_id_to_url(dw_id)
        if new is None:
            continue
        kept.append((old, new))

    # Deterministic order: by old URL.
    kept.sort()

    lines = [PREAMBLE]
    lines.append("# Per-page redirects (one line per DokuWiki page)\n")
    for old, new in kept:
        # Escape regex specials in the old path; DokuWiki ids only use
        # ASCII letters, digits, underscore, hyphen, and colon (we already
        # converted ':' -> '/'), so we just need to anchor and add an
        # optional trailing slash.
        old_re = old.lstrip("/")
        # If the URL contains '.', escape it.
        old_re = old_re.replace(".", "\\.")
        lines.append(f"RewriteRule ^{old_re}/?$ {new} [R=301,L]\n")

    lines.append(DROP_BLOCK)
    for ns in DROP_NAMESPACES:
        lines.append(f"RewriteRule ^{ns}(/.*)?$ / [R=301,L]\n")

    lines.append("\n# Fallback: anything we missed -> home (302 so we can fix later)\n")
    lines.append("# Uncomment after smoke-testing the per-page redirects above.\n")
    lines.append("# RewriteCond %{REQUEST_FILENAME} !-f\n")
    lines.append("# RewriteCond %{REQUEST_FILENAME} !-d\n")
    lines.append("# RewriteRule ^.*$ / [R=302,L]\n")

    args.out.write_text("".join(lines), encoding="utf-8")
    print(f"  wrote {args.out} ({len(kept)} per-page redirects)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
